---
title: "R Notebook"
output: html_notebook
---

TP - 1

Data

```{r}
age = c(24,26,29,31,33,37,38, 41,43,45,46,49,50,52,57,59,60,62)
effectif = c(1,2,3,2,4,2,4,3,3,1,6,3,1,3,5,2,2,1)


total_individu = sum(effectif)
frequence = round(((effectif / total_individu) * 100), 2)

total_effectif = cumsum(effectif)
total_frequence = cumsum(frequence)

print(paste('total_individu : ', total_individu))
print(frequence)
print(total_effectif)
print(total_frequence)


```

Tableaux

```{r}

df <- data.frame(
  age,
  effectif,
  total_effectif,
  frequence,
  total_frequence
)

print(df)

```

Diagramme batons

```{r}

plot(age, effectif, 
     type='h',
     lwd=1,
     col = "Blue", 
     xlab = "Age", 
     ylab = "Effectif", 
     main = "Diagramme en bâtons",
     xlim = c(20,70),
     ylim = c(0, 6)
)

```

Diagramme cumulatif

```{r}

plot(age, total_effectif, type = 's', lwd = 1, col = "blue", 
     xlab = "Age", 
     ylab = "Effectifs cumulés", 
     main = "Diagramme cumulatif",
     xlim = c(20,70),
     ylim = c(0,50),
    )

```

Calcule de la médiane, quartiles, moyenne, dispersion, variance et ecart-type :

```{r}

mediane = median(age)
quantiles = quantile(age)

age_effectif = age * effectif

somme_age_effectif = sum(age_effectif)
somme_effectifs = sum(total_individu)
moyenne = somme_age_effectif / somme_effectifs
variance =  sum(effectif * (age - moyenne)^2) / sum(effectif)
ecart_type = sqrt(variance)

dispersion = max(age) - min(age)

print(paste('Médiane : ', mediane))
print(paste('Moyenne : ', moyenne))
print(paste('Quantile 1/4 : ', round(quantiles["25%"])))
print(paste('Quantile 1/2 : ', round(quantiles["50%"])))
print(paste('Quantile 3/4 : ', round(quantiles["75%"])))
print(paste('Variance : ',  round(variance, 4)))
print(paste('Ecart-type : ',  round(ecart_type,1)))
print(paste('Dispersion : ', dispersion))
```

Diagramme boite a moustaches

```{r}


boxplot(age,
        main = "Diagramme en Boîte à Moustaches",
        ylab = "Valeurs",
        col = "lightblue",
        border = "black",
        boxwex = 0.5,
        notch = TRUE,
        horizontal = FALSE
       )

y_ticks <- axTicks(2) 
abline(h = y_ticks, col = "black", lty = 2) 

text(x = 1, y = quantiles["0%"], labels = paste("Q0:", round(quantiles["0%"], 0)), pos = 4, col = "black")
text(x = 1, y = quantiles["25%"], labels = paste("Q1:", round(quantiles["25%"], 0)), pos = 4, col = "black")
text(x = 1, y = quantiles["75%"], labels = paste("Q3:", round(quantiles["75%"], 0)), pos = 4, col = "black")
text(x = 1, y = quantiles["100%"], labels = paste("Q4:", round(quantiles["100%"], 0)), pos = 4, col = "black")
text(x = 1.08, y = median(age), labels = paste("Médiane:", round(median(age), 0)), pos = 4, col = "black")
text(x = 0.70, y = moyenne, labels = paste("Moyenne:", round(moyenne, 2)), pos = 4, col = "black")

```
