---
title: "R Notebook"
output: html_notebook
---

# Analyse

```{r}

evans <- read.table("http://web1.sph.emory.edu/dkleinb/allDatasets/datasets/evans.dat")
head(evans)


```


```{r}

names(evans) <- c("id","chd","cat","age","chl","smk","ecg","dbp","sbp","hpt","ch","cc")
head(evans) 


```

```{r}

boxplot(evans$cat ~ evans$chd, 
        main = "Catecholamine Levels by Coronary Heart Disease Status",
        xlab = "Presence of CHD (1 = Yes, 0 = No)",
        ylab = "Catecholamine Levels",
        col = c("lightblue", "lightgreen"))

```
```{r}

myreg_simple <- glm(evans$chd ~ evans$cat, family = binomial(link = "logit"))

summary(myreg_simple)

```
   
   
```{r}
exp(coef(myreg_simple))

  
```

```{r}
cat_seq <- seq(min(evans$cat), max(evans$cat), length.out = 100)
new_data <- data.frame(cat = cat_seq)
pred_prob_simple <- predict(myreg_simple, newdata = new_data, type = "response")

print(length(cat_seq))         
print(length(pred_prob_simple))
```

```{r}

length(evans$smk)
length(ypredit)
```